const messages = {
    navigation: {
        dashboard: "Dashboard",
        events: "Events",
        orders: "Orders",
        finance: "Finance",
        settings: "Settings",
        selectOrganization: "Select Organization",
        signIn: "Sign In",
        signUp: "Sign Up",
        byde: "byde",
        filter: "Filter",
        cancel: "Cancel",
        confirm: "Confirm",
        viewEvents: "View Events",
        viewFinance: "View Finance",
        withdraw: "Withdraw",
        createEvent: "Create an event",
        back: "Back"
    },
    dashboard: {
        welcomeBack: "Welcome back {name}",
        quickActions: "Quick Actions",
        salesOverview: "Sales Overview",
        upcomingEvents: "Upcoming Events",
        ticketSales: "Ticket Sales",
        wallet: "Wallet"
    },
    events: {
        name: "Name",
        date: "Date",
        ticketsSold: "Tickets Sold",
        revenue: "Revenue",
        status: "Status"
    },
    orders: {
        orderId: "Order ID",
        event: "Event",
        buyer: "Buyer",
        date: "Date",
        total: "Total",
        status: "Status",
        refundMethod: "Refund Method",
        orderNotFound: "Order not found"
    },
    finance: {
        payouts: "Payouts",
        bankAccounts: "Bank Accounts",
        amount: "Amount",
        date: "Date",
        name: "Name",
        bank: "Bank",
        dateAdded: "Date Added",
        accountNumber: "Account Number",
        accountType: "Account Type",
        country: "Country",
        currency: "Currency",
        status: "Status"
    },
    status: {
        live: "Live",
        draft: "Draft",
        pending: "Pending",
        ended: "Ended",
        paid: "Paid",
        cancelled: "Cancelled",
        refunded: "Refunded",
        underReview: "Under Review",
        rejected: "Rejected",
        verified: "Verified",
        unverified: "Unverified"
    },
    modals: {
        createEvent: {
            title: "Are you absolutely sure?",
            description: "This action cannot be undone. Are you sure you want to permanently delete this file from our servers?"
        }
    },
    settings: {
        title: "Settings",
        description: "Manage your account settings and preferences.",
        account: "Account"
    },
    common: {
        name: "Name",
        date: "Date",
        status: "Status",
        amount: "Amount",
        total: "Total",
        filter: "Filter",
        cancel: "Cancel",
        confirm: "Confirm",
        back: "Back",
        orderNotFound: "Order not found",
        currency: {
            GBP: "£",
            USD: "$",
            EUR: "€",
            CAD: "CA$",
            AUD: "A$",
            NZD: "NZ$",
            CHF: "CHF",
            JPY: "¥"
        }
    },
    metadata: {
        title: "Create Next App",
        description: "Generated by create next app"
    },
    pagination: {
        previous: "Previous",
        next: "Next"
    },
    actions: {
        view: "View",
        edit: "Edit",
        delete: "Delete",
        create: "Create",
        save: "Save",
        update: "Update"
    }
}

export default messages